### ISSUE TITLE
invalid api call

### ISSUE THREAD

**Issue by nexaas** [THINK989/Real-Time-Stock-Market-Prediction-using-Ensemble-DL-and-Rainbow-DQN#4]
hi , thanks for this repository ,I have type NSEI as stock and selt 5 min but there is an api call error, do you have any idea about this error, maybe I select wrong paramaters,

and  can u give some informations about updates in trading-repository,which strategy/epsisode  is best in your opinion

Stock to plot: NSEI
Enter the amount of interval among 1, 5, 15 and 30:-5
Currently Pulling NSEI
Traceback (most recent call last):
  File "C:\Python38\lib\site-packages\matplotlib\cbook\__init__.py", line 196, in process
    func(*args, **kwargs)
  File "C:\Python38\lib\site-packages\matplotlib\animation.py", line 951, in _start
    self._init_draw()
  File "C:\Python38\lib\site-packages\matplotlib\animation.py", line 1743, in _init_draw
    self._draw_frame(next(self.new_frame_seq()))
  File "C:\Python38\lib\site-packages\matplotlib\animation.py", line 1766, in _draw_frame
    self._drawn_artists = self._func(framedata, *self._args)
  File "C:/Users/ahmet/PycharmProjects/Real-Time-Stock-Market-Prediction-using-Ensemble-DL-and-Rainbow-DQN/animate.py", line 276, in animate
    graphData(stock,10,50,interval)
  File "C:/Users/ahmet/PycharmProjects/Real-Time-Stock-Market-Prediction-using-Ensemble-DL-and-Rainbow-DQN/animate.py", line 111, in graphData
    data, meta_data = ts.get_intraday(symbol=stock,interval=str(interval)+'min')
  File "C:\Python38\lib\site-packages\alpha_vantage\alphavantage.py", line 218, in _format_wrapper
    call_response, data_key, meta_data_key = func(
  File "C:\Python38\lib\site-packages\alpha_vantage\alphavantage.py", line 160, in _call_wrapper
    return self._handle_api_call(url), data_key, meta_data_key
  File "C:\Python38\lib\site-packages\alpha_vantage\alphavantage.py", line 337, in _handle_api_call
    raise ValueError(json_response["Error Message"])
ValueError: Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_INTRADAY.
Plot will update every 5 minutes
Stock to plot:

**Comment by THINK989** [comment]
Hello @nexaas ,
**Nifty50(NSEI)** is called using **^NSEI** symbol

**Comment by nexaas** [comment]
yes other symbols works, thanks

**Comment by nexaas** [comment]
> Hey @nexaas ,
> Also, remember Alpha vantage allows only 5 calls per minute and 500 calls per day.

ok , thank you
